server {
    listen 80;
    listen [::]:80;
    server_name korath.ovh www.korath.ovh;
    return 301 https://korath.ovh$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name korath.ovh www.korath.ovh;

    ssl_certificate     /etc/letsencrypt/live/korath.ovh/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/korath.ovh/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

    include /etc/nginx/snippets/security-headers.conf;

    root  /var/www/html/korath.ovh;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    access_log /var/log/nginx/korath.ovh.access.log main;
    error_log  /var/log/nginx/korath.ovh.error.log warn;
}
