name: Deploy Website to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build production
        run: npm run build

      - name: Prepare remote deploy directory
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            mkdir -p /var/www/html/korath.ovh
            find /var/www/html/korath.ovh -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +

      - name: Upload build artifacts
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: dist/korath/browser/*
          target: /var/www/html/korath.ovh
          strip_components: 3
          overwrite: true
